spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: erkan
    password: 123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

secret:
  jwt-key: bill-ge-oss-vg