spring:

  datasource:
    url: jdbc:mysql://localhost:3306/dateathletic
    username: root
    password: bigboydb123




  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

secret:
  jwt-key: bill-ge-oss-vg

